name: Go CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
          
      - name: Install Dependencies
        run: go mod download
        
      - name: Install GolangCI-Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        
      - name: Lint
        run: golangci-lint run ./...
        
      - name: Test
        run: go test ./...
