name: Next.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Clear npm cache
        run: npm cache clean --force
          
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        
      - name: Lint
        run: npm run lint
        
      - name: Format Check
        run: npm run format:check
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm test
