name: WordPress CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Install Composer
        run: sudo apt-get install -y composer
        
      - name: Install Dependencies
        run: composer install
        
      - name: Install PHPCS
        run: composer global require "squizlabs/php_codesniffer=*"
        
      - name: Lint
        run: ~/.composer/vendor/bin/phpcs --standard=WordPress ./path/to/your/php/files
        
      - name: Test
        run: ./vendor/bin/phpunit
